### ISSUE TITLE
Android ppsspp crash issue

### ISSUE THREAD

**Issue by YashuTyagi872** [thyjukki/NZP-Reboot#65]
The homebrew just crashes the ppsspp android app when i try to open it, help me please, i want to play this remastered version of the original homebrew so bad

**Comment by MotoLegacy** [comment]
Hey there, to our knowledge, there isn't any clear and cut way to get NZ:P booting under PPSSPP Android. Presumably due to the range of hardware it runs on. The best advice I could give is to play around with the graphics and system settings in the emulator until you get a combination that boots. Sorry, wish I could be of more help. Closing.
